// Generated by LiveScript 1.2.0
var budgetCtrl;
budgetCtrl = function($scope){
  var inspector, inspector_dept, inspector_inst, radius, color;
  inspector = d3.select('body').append('div').attr('class', 'inspector').style('opacity', 0);
  inspector_dept = inspector.append('p');
  inspector_inst = inspector.append('p');
  radius = 900;
  color = d3.scale.category20c();
  color = d3.scale.ordinal().range(['#F6B4FF', '#AA8BE8', '#86A0FF', '#A6D7E8', '#C0FFEC']);
  import$($scope, {
    inst: "",
    name: "",
    query: "",
    update: function(){
      d3.select('#svg').selectAll('g.inst circle.inst').attr('fill', function(it){
        if (it.inst) {
          return color(it.inst);
        } else {
          return 'none';
        }
      }).transition().duration(750).attr('r', function(it){
        if ($scope.query && it.name && it.name.indexOf($scope.query) >= 0 && $scope.query !== '') {
          return 100;
        }
        if ($scope.query !== '') {
          return 10;
        }
        return it.r;
      }).style('opacity', function(it){
        if ($scope.query && it.name && it.name.indexOf($scope.query) >= 0 && $scope.query !== '') {
          return 1;
        }
        if ($scope.query !== '') {
          return 0.5;
        }
        return 1;
      }).transition().duration(1000).attr('transform', function(it){
        if ($scope.query && it.name && it.name.indexOf($scope.query) >= 0 && $scope.query !== '') {
          return "translate(" + 0 + " " + 0 + ")";
        }
        if ($scope.query !== '') {
          return "translate(" + 400 + " " + (800 - it.y) + ")";
        }
        return "translate(" + 0 + " " + 0 + ")";
      });
      return d3.select('#svg').selectAll('text').text(function(it){
        if ($scope.query && it.name && it.name.indexOf($scope.query) >= 0 && $scope.query !== '') {
          return it.name;
        }
        if ($scope.query !== '') {
          return "";
        }
        if (it.r > 15) {
          return it.name;
        } else {
          return "";
        }
      }).style('opacity', function(it){
        if ($scope.query && it.name && it.name.indexOf($scope.query) >= 0 && $scope.query !== '') {
          return 1;
        }
        if ($scope.query !== '') {
          return 0;
        }
        return 1;
      }).style('font-size', function(it){
        if ($scope.query && it.name && it.name.indexOf($scope.query) >= 0 && $scope.query !== '') {
          return 20;
        }
        return 10;
      });
    }
  });
  $scope.$watch('query', function(){
    console.log($scope.query);
    return $scope.update();
  });
  return d3.json('budget.json', function(data){
    var bubble, svg, root, instHash, circleHash, key, dept, x$, y$, z$, z1$;
    bubble = d3.layout.pack().sort(null).size([radius, radius]).padding(1.5);
    svg = d3.select('#svg');
    root = {
      children: []
    };
    instHash = {};
    circleHash = {};
    root = {
      children: (function(){
        var results$ = [];
        for (key in data) {
          results$.push({
            name: key,
            inst: key,
            value: Math.sqrt(data[key][0]),
            c: (fn$())
          });
        }
        return results$;
        function fn$(){
          var ref$, results$ = [];
          for (dept in data[key][1]) {
            results$.push({
              name: dept,
              inst: key,
              value: Math.sqrt((ref$ = data[key][1][dept]) > 1 ? ref$ : 1)
            });
          }
          return results$;
        }
      }())
    };
    x$ = svg.selectAll('g.inst').data(bubble.nodes(root));
    y$ = x$.enter();
    z$ = y$.append('g').attr('class', 'inst');
    z$.attr('transform', function(it){
      return "translate(" + it.x + " " + it.y + ")";
    });
    z$.append('circle').attr('class', 'inst').attr('r', function(it){
      return it.r;
    }).attr('fill', function(it){
      if (it.inst) {
        return color(it.inst);
      } else {
        return 'none';
      }
    }).call(function(it){
      return circleHash[it.name] = this;
    }).each(function(d){
      var parent, this$ = this;
      parent = d3.select(this)[0][0].parentElement;
      d3.select(parent).on('click', function(e){
        if (this$.r.baseVal.value < 100) {
          $scope.query = d.name;
          $scope.update();
        } else {
          $scope.query = '';
          $scope.update();
        }
        return d3.select(parent).selectAll('g.dept').style('opacity', 0);
      });
      d3.select(parent).on('mouseover', function(e){
        var cur_r, bubble, x$, y$;
        cur_r = this$.r.baseVal.value;
        $scope.$apply(function(e){
          return $scope.inst = d.inst;
        });
        bubble = d3.layout.pack().sort(null).size([2 * cur_r, 2 * cur_r]).padding(1.5);
        if (d.c.length > 0) {
          x$ = d3.select(parent).selectAll('g.dept').data(bubble.nodes({
            children: d.c
          }));
          y$ = x$.enter().append('g').attr('class', 'dept');
          y$.append('circle').attr('r', function(it){
            return it.r;
          }).attr('fill', function(it){
            if (it.name) {
              return color(it.name);
            } else {
              return 'none';
            }
          }).on('mouseover', function(it){
            $scope.$apply(function(e){
              return $scope.name = it.name;
            });
            inspector.transition().duration(200).style('opacity', 0.9);
            inspector_inst.text(it.name);
            inspector_dept.text(d.inst);
            inspector.style('left', (d3.event.pageX + 30) + "px");
            return inspector.style('top', d3.event.pageY + "px");
          }).on('mouseout', function(it){
            return inspector.transition().duration(500).style('opacity', 0.0);
          });
          d3.select(parent).selectAll('g.dept').data(bubble.nodes({
            children: d.c
          })).selectAll('circle').attr('r', function(it){
            return it.r;
          }).attr('transform', function(it){
            return "translate(" + (it.x - cur_r) + " " + (it.y - cur_r) + ")";
          });
        }
        return d3.select(parent).selectAll('g.dept').style('opacity', 1);
      });
      return d3.select(parent).on('mouseout', function(e){
        return d3.select(parent).selectAll('g.dept').style('opacity', 0);
      });
    });
    z1$ = y$.append('g').attr('class', 'inst-text');
    z1$.attr('transform', function(it){
      return "translate(" + it.x + " " + it.y + ")";
    });
    z1$.append('text').attr('class', 'name').text(function(it){
      if (it.r > 15) {
        return it.name;
      } else {
        return "";
      }
    }).style('font-size', function(){
      return 10;
    });
    return x$;
  });
};
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}